Playwright UI mode
ZEISS/angular-styleguide pull request #6
Opened 2023-08-25 14:05 UTC by manuel-mauky

This PR updates playwright to the newest version to have [Playwright UI mode](https://playwright.dev/docs/test-ui-mode) available.
Additionally it adds a package.json script to start UI mode.

2023-08-25 15:25 UTC, manuel-mauky commented
It looks as if webdriver-io is using system-installed browsers.
This is not related to this PR because I get the same error when running the tests on the main branch.

I think the root-cause is that it's depending on system browsers. A better approach would be to pin the browser versions being used.
I'm not sure if webdriver-io provides this feature. I know that playwright brings its own browsers and we maybe _could_ configure webdriver-io in a way to use the playwright browsers.

2023-08-28 09:04 UTC, sbley requested changes

2023-08-28 09:04 UTC, sbley commented on README.md
> +Run `npm run e2e:playwright:ui` to start [Playwrite UI-Mode](https://playwright.dev/docs/test-ui-mode).
```suggestion
Run `npm run e2e:playwright:ui` to start [Playwright UI Mode](https://playwright.dev/docs/test-ui-mode).
```

2023-08-28 09:15 UTC, sbley approved these changes

2023-11-17 08:14 UTC, merged